export { default as Nav } from "./Nav";
export { default as Home } from "./Home";
export { default as Hero } from "./Hero";
export { default as Section } from "./Section";
export { default as Solutions } from "./Solutions";
export { default as Services } from "./Services";
export { default as Cities } from "./Cities";
export { default as About } from "./About";
export { default as Footer } from "./Footer";
